// Generated by gencpp from file ros_msg/RobotStateInfo.msg
// DO NOT EDIT!


#ifndef ROS_MSG_MESSAGE_ROBOTSTATEINFO_H
#define ROS_MSG_MESSAGE_ROBOTSTATEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_msg
{
template <class ContainerAllocator>
struct RobotStateInfo_
{
  typedef RobotStateInfo_<ContainerAllocator> Type;

  RobotStateInfo_()
    : header()
    , s(0.0)
    , JointState()
    , CartPose()  {
    }
  RobotStateInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , s(0.0)
    , JointState(_alloc)
    , CartPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _s_type;
  _s_type s;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _JointState_type;
  _JointState_type JointState;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _CartPose_type;
  _CartPose_type CartPose;





  typedef boost::shared_ptr< ::ros_msg::RobotStateInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_msg::RobotStateInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStateInfo_

typedef ::ros_msg::RobotStateInfo_<std::allocator<void> > RobotStateInfo;

typedef boost::shared_ptr< ::ros_msg::RobotStateInfo > RobotStateInfoPtr;
typedef boost::shared_ptr< ::ros_msg::RobotStateInfo const> RobotStateInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_msg::RobotStateInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_msg::RobotStateInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_msg': ['/home/rokae/catkin_ws/src/ros_core/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::RobotStateInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::RobotStateInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::RobotStateInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6992e685e364f996373c626aa137c2a7";
  }

  static const char* value(const ::ros_msg::RobotStateInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6992e685e364f996ULL;
  static const uint64_t static_value2 = 0x373c626aa137c2a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_msg/RobotStateInfo";
  }

  static const char* value(const ::ros_msg::RobotStateInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 s\n\
float64[] JointState\n\
float64[] CartPose  \n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ros_msg::RobotStateInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.s);
      stream.next(m.JointState);
      stream.next(m.CartPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStateInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_msg::RobotStateInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_msg::RobotStateInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "JointState[]" << std::endl;
    for (size_t i = 0; i < v.JointState.size(); ++i)
    {
      s << indent << "  JointState[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.JointState[i]);
    }
    s << indent << "CartPose[]" << std::endl;
    for (size_t i = 0; i < v.CartPose.size(); ++i)
    {
      s << indent << "  CartPose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.CartPose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSG_MESSAGE_ROBOTSTATEINFO_H
